// Generated by CoffeeScript 1.10.0
$(function() {
  return $('.clouds i, .title span span').hover(function() {
    return $(this).addClass('hover');
  }, function() {
    return $(this).removeClass('hover');
  });
});
